### ISSUE TITLE
"y" argument not parsed

### ISSUE THREAD

**Issue by pavel-georgiev** [ghodss/yaml#14]
After parsing the following yaml :

```
x: 10
y: 20
```

x is being extracted, but y is not. Changing 'y' to anything else works.

Reproducible sample:

```
package main

import (
    "fmt"
    "github.com/ghodss/yaml"
)

type Position struct {
    X int `json:"x"`
    Y int `json:"y"`
}

func main() {
    s := []byte(`
x: 10
y: 20
`)

    var p Position
    err := yaml.Unmarshal(s, &p)
    if err != nil {
        fmt.Printf("err: %v\n", err)
        return
    }
    fmt.Println(p) // Should be {10 20}, but prints {10 0}
}

```

**Comment by pavel-georgiev** [comment]
The example above prints {10 0} instead of {10 20}

**Comment by lwalen** [comment]
Confusingly, it looks like this is part of YAML: http://yaml.org/type/bool.html. From the linked page, we see that any key or value that matches the following pattern is considered a boolean:
```
y|Y|yes|Yes|YES|n|N|no|No|NO|true|True|TRUE|false|False|FALSE|on|On|ON|off|Off|OFF
```

This is reflected in this project [here](https://github.com/ghodss/yaml/blob/master/yaml.go#L157), where the key is changed to the string `"true"`. It actually continues marshaling the value too, so if your struct had a ``Y int `json:"true"` `` or `True int` field, its value would be 20.

To get around this, you can quote the `y` in your YAML. Both single and double quotes seemed to work fine.

**Comment by snarfbeest** [comment]
Sorry to butt in - I hit this issue as well. The above-mentioned "boolean pattern" is defined *only* in yaml-1.1 - and is marked as a *draft*. The current specification (yaml 1.2: http://www.yaml.org/spec/1.2/spec.html) has none of this - and the overview explicitly states that this has been removed (along with other "implicit typing rules"). BTW, current YAML parsers in other languages (e.g., Python) don't do this, either. IMO, this "feature" should be removed.

**Comment by pnickolov** [comment]
👍 

@lwalen, thanks for the workaround - it does help. Still, things break if we have to parse externally provided files (e.g., ones generated by humans, pythons or other non-Go creatures) rather than yaml files specially crafted to work around this issue

If the old behavior is desirable for backward compatibility (unlikely), the old behavior can be preserved  through an option. Considering that the latest YAML spec (1.2, see @snarfbeest comment) does not require/allow for this behavior, I would propose the default to be off (i.e., compliant with the latest spec); if we really must keep this behavior by default, it will still be better to have the proper parsing to be available even if we have to request it explicitly.

**Comment by ghodss** [comment]
Unfortunately, this behavior is controlled by the go-yaml package that this package depends on - this package doesn't parse out what a boolean is, it just trusts go-yaml to tell it which values are booleans and uses that derived information. If you'd like go-yaml to expose an option to change its behavior, you can chime in on this PR here https://github.com/go-yaml/yaml/pull/222 ... if they expose the option I'd be happy to utilize it in my library as well.

**Comment by ghodss** [comment]
Closing for now since there is no action unless go-yaml exposes an option.
