### ISSUE TITLE
Cast Variable Values As String

### ISSUE THREAD

**Issue by pnovotnak** [ghodss/yaml#5]
Not sure if this is the right place to report this or not, but I'm running into an issue in a downstream project. The exact error is:

    json: cannot unmarshal number into Go value of type string

https://github.com/kubernetes/kubernetes/issues/12889

And the [source code](https://github.com/kubernetes/kubernetes/blob/d239d51f3acc663bf16f567be9a0e6f812c4f1dd/pkg/util/yaml/decoder.go#L38)

If you believe this is *not* the right place and you have a moment, please point me in the right direction.

Thanks much!

**Comment by ghodss** [comment]
If you use YAML, coercion from int to string should happen automatically because in yaml, quotes are optional. If you use JSON though, we try to be type safe and alert if you are passing one type into a struct which expects a different type. As such this is expected behavior.

Feel free to reopen if I've misunderstood.
